version: '3'

services:
  # Creates a Containor 
  db:
   # specifies the postgres image i want in my containor
    image: postgres:alpine
    # specifies the ports that the containor will run on 
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=units
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=ambria26
    volumes:
        - ./express_server/init.sql:/docker-entrypoint-initdb.d/init.sql

  #app:
    #Tell what dockerfile is needed to build the containor
    #build: my-search/
    #instructs how to start app
    #command: npm start
    #environment:
     # - DATABASE_URL=postgres://me:ambria26@db:5432
     # - NODE_ENV=test
    #depends_on:
      #db:
        #condition: service_healthy
     #links:
     #- db
    #ports:
     #- 3000:3000

  api: 
    build: express_server/
    command: npm start
    depends_on:
      - db
    links:
     - db
    ports: 
      - '3010:3010'


